# Generated by Django 3.1 on 2020-08-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=32)),
                ('ean', models.CharField(max_length=32)),
                ('marketplace', models.CharField(max_length=32)),
                ('isDelete', models.SmallIntegerField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'blacklist_products',
            },
        ),
        migrations.AddIndex(
            model_name='blacklistproducts',
            index=models.Index(fields=['asin', 'ean', 'marketplace'], name='asineanmarketplace_unique_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blacklistproducts',
            unique_together={('asin', 'ean', 'marketplace')},
        ),
    ]
