# Generated by Django 3.1 on 2020-08-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200828_0543'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blacklistproducts',
            name='asineanmarketplace_unique_idx',
        ),
    ]
