# Generated by Django 3.1 on 2020-08-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200828_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistproducts',
            name='isDelete',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
