export const marketplaces = [
  { label: 'ALL', value: 'ALL' },
  { label: 'CDISCOUNT', value: 'CDISCOUNT' },
  { label: 'FNAC', value: 'FNAC' },
  { label: 'RAKUTEN', value: 'RAKUTEN' },
  { label: 'DARTY', value: 'DARTY' },
  { label: 'EBAY', value: 'EBAY' },
  { label: 'AMAZON', value: 'AMAZON' },
  { label: 'CARREFOUR', value: 'CARREFOUR' },
  { label: 'WORTEN', value: 'WORTEN' },
  { label: 'REAL', value: 'REAL' },
  { label: 'OTTO', value: 'OTTO' },
  { label: 'EPRICE', value: 'EPRICE' },
  { label: 'IBS', value: 'IBS' },
  { label: 'BOL', value: 'BOL' },
  { label: 'BESTLIST', value: 'BESTLIST' },
  { label: 'ALLEGRO', value: 'ALLEGRO' },
  { label: 'OLX', value: 'OLX' },
  { label: 'COOLBLUE', value: 'COOLBLUE' },
  { label: 'VANDEN BORRE', value: 'VANDENBORRE' },
  { label: 'ARGOS', value: 'ARGOS' },
  { label: 'FRUUGO', value: 'FRUUGO' },
  { label: 'EMAG', value: 'EMAG' },
  { label: 'RICARDO', value: 'RICARDO' },
  { label: 'HEUREKA', value: 'HEUREKA' }
];
